### PR TITLE
feature-tidy

### PR DESCRIPTION
**Pull request by johnpapa**
- Prettier and eslint
- remove dead code (80+ lines)
- fix social media preset bug (fixes issue #7)
- barrel for modules, shorten imports
- remove .vue extension
- link card is own component
- move link card so screen doesnt visually jump
- preset formatting

### CODE REVIEW

**Comment by johnpapa** [comment]
please squash merge, after you are comfortable with this PR

**Comment by spboyer** [comment]
@johnpapa build failed with prettier errors

https://dev.azure.com/shayneboyer/social-linker/_build/results?buildId=457

**Comment by johnpapa** [comment]
Good catch. I’ll fix

**Comment by johnpapa** [comment]
@spboyer we may want to add a `npm run lint` in the pipeline. I looked at the pipeline file and I do not see the steps to build the app. I was expecting to see something like ...

```bash
npm install
npm run lint
npm run build
```

**Pull request merged**
